using System;
using System.IO;

namespace Kinship
{
    public class FamilyTerms
    {

        public string GetRelationship(string RelationshipString)
        {
            switch (RelationshipString.Length)
            {
                case 0:
                    return Ego;
                case 1:
                    switch (RelationshipString[0])
                    {
                        case 'F':
                            return Father;
                        case 'M':
                            return Mother;
                        case 'B':
                            return Brother;
                        case 'Z':
                            return Sister;
                        case 'S':
                            return Son;
                        case 'D':
                            return Daughter;
                        case 'P':
                            return Partner;
                        default:
                            return Error;
                    }
                case 2:
                    switch (RelationshipString)
                    {
                        case "FF": return GrandFather;
                        case "FM": return Nanna:
                        case "FB": return Faedro;
                        case "FZ": return Aunt;
                        case "FS": return AgnaticBrother;
                        case "FD": return AgnaticSister;
                        case "FP": return StepMother;
                        case "MF": return GenGen;
                        case "MM": return GrandMother;
                        case "MB": return Uncle;
                        case "MZ": return Modrie;
                        case "MS": return UterineBrother;
                        case "MD": return UterineSister;
                        case "MP": return StepFather;
                        case "BF": return Father;
                        case "BM": return Mother;
                        case "BB": return Brother;
                        case "BZ": return Sister;
                        case "BS": return Nephew;
                        case "BD": return Niece;
                        case "BP": return Jeneter;
                        case "ZF": return Father;
                        case "ZM": return Mother;
                        case "ZB": return Brother;
                        case "ZZ": return Sister;
                        case "ZS": return Maphew;
                        case "ZD": return Mitolina;
                        case "ZP": return Levir;
                        case "SF": return Ego;
                        case "SM": return Wife;
                        case "SB": return Son;
                        case "SZ": return Daughter;
                        case "SS": return GrandSon;
                        case "SD": return PaternalGranddaughter;
                        case "SP": return Schnerre;
                        case "DF": return Ego;
                        case "DM": return Ego;
                        case "DB": return Son;
                        case "DZ": return Daughter;
                        case "DS": return DaughterSon;
                        case "DD": return GrandDaughter;
                        case "DP": return Yerno;
                        case "PF": return Sweger;
                        case "PM": return Swegra;
                        case "PB": return Levir;
                        case "PZ": return Jeneter;
                        case "PS": return StepSon;
                        case "PD": return StepDaughter;
                        case "PP": return Jeneter;
                        default: return Error;
                    }
                case 3:
                    switch (RelationshipString)
                    {
                        case "FFF": return MLMK^$;
                        case "FFM": return MLMK^$;
                        case "FFB": return MLMK^$;
                        case "FFZ": return MLMK^$;
                        case "FFS": return MLMK^$;
                        case "FFD": return MLMK^$;
                        case "FFP": return MLMK^$;
                        case "FMF": return MLMK^$;
                        case "FMM": return MLMK^$;
                        case "FMB": return MLMK^$;
                        case "FMZ": return MLMK^$;
                        case "FMS": return MLMK^$;
                        case "FMD": return MLMK^$;
                        case "FMP": return MLMK^$;
                        case "FBF": return MLMK^$;
                        case "FBM": return MLMK^$;
                        case "FBB": return MLMK^$;
                        case "FBZ": return MLMK^$;
                        case "FBS": return MLMK^$;
                        case "FBD": return MLMK^$;
                        case "FBP": return MLMK^$;
                        case "FZF": return MLMK^$;
                        case "FZM": return MLMK^$;
                        case "FZB": return MLMK^$;
                        case "FZZ": return MLMK^$;
                        case "FZS": return MLMK^$;
                        case "FZD": return MLMK^$;
                        case "FZP": return MLMK^$;
                        case "FSF": return MLMK^$;
                        case "FSM": return MLMK^$;
                        case "FSB": return MLMK^$;
                        case "FSZ": return MLMK^$;
                        case "FSS": return MLMK^$;
                        case "FSD": return MLMK^$;
                        case "FSP": return MLMK^$;
                        case "FDF": return MLMK^$;
                        case "FDM": return MLMK^$;
                        case "FDB": return MLMK^$;
                        case "FDZ": return MLMK^$;
                        case "FDS": return MLMK^$;
                        case "FDD": return MLMK^$;
                        case "FDP": return MLMK^$;
                        case "FPF": return MLMK^$;
                        case "FPM": return MLMK^$;
                        case "FPB": return MLMK^$;
                        case "FPZ": return MLMK^$;
                        case "FPS": return MLMK^$;
                        case "FPD": return MLMK^$;
                        case "FPP": return MLMK^$;
                        case "MFF": return MLMK^$;
                        case "MFM": return MLMK^$;
                        case "MFB": return MLMK^$;
                        case "MFZ": return MLMK^$;
                        case "MFS": return MLMK^$;
                        case "MFD": return MLMK^$;
                        case "MFP": return MLMK^$;
                        case "MMF": return MLMK^$;
                        case "MMM": return MLMK^$;
                        case "MMB": return MLMK^$;
                        case "MMZ": return MLMK^$;
                        case "MMS": return MLMK^$;
                        case "MMD": return MLMK^$;
                        case "MMP": return MLMK^$;
                        case "MBF": return MLMK^$;
                        case "MBM": return MLMK^$;
                        case "MBB": return MLMK^$;
                        case "MBZ": return MLMK^$;
                        case "MBS": return MLMK^$;
                        case "MBD": return MLMK^$;
                        case "MBP": return MLMK^$;
                        case "MZF": return MLMK^$;
                        case "MZM": return MLMK^$;
                        case "MZB": return MLMK^$;
                        case "MZZ": return MLMK^$;
                        case "MZS": return MLMK^$;
                        case "MZD": return MLMK^$;
                        case "MZP": return MLMK^$;
                        case "MSF": return MLMK^$;
                        case "MSM": return MLMK^$;
                        case "MSB": return MLMK^$;
                        case "MSZ": return MLMK^$;
                        case "MSS": return MLMK^$;
                        case "MSD": return MLMK^$;
                        case "MSP": return MLMK^$;
                        case "MDF": return MLMK^$;
                        case "MDM": return MLMK^$;
                        case "MDB": return MLMK^$;
                        case "MDZ": return MLMK^$;
                        case "MDS": return MLMK^$;
                        case "MDD": return MLMK^$;
                        case "MDP": return MLMK^$;
                        case "MPF": return MLMK^$;
                        case "MPM": return MLMK^$;
                        case "MPB": return MLMK^$;
                        case "MPZ": return MLMK^$;
                        case "MPS": return MLMK^$;
                        case "MPD": return MLMK^$;
                        case "MPP": return MLMK^$;
                        case "BFF": return MLMK^$;
                        case "BFM": return MLMK^$;
                        case "BFB": return MLMK^$;
                        case "BFZ": return MLMK^$;
                        case "BFS": return MLMK^$;
                        case "BFD": return MLMK^$;
                        case "BFP": return MLMK^$;
                        case "BMF": return MLMK^$;
                        case "BMM": return MLMK^$;
                        case "BMB": return MLMK^$;
                        case "BMZ": return MLMK^$;
                        case "BMS": return MLMK^$;
                        case "BMD": return MLMK^$;
                        case "BMP": return MLMK^$;
                        case "BBF": return MLMK^$;
                        case "BBM": return MLMK^$;
                        case "BBB": return MLMK^$;
                        case "BBZ": return MLMK^$;
                        case "BBS": return MLMK^$;
                        case "BBD": return MLMK^$;
                        case "BBP": return MLMK^$;
                        case "BZF": return MLMK^$;
                        case "BZM": return MLMK^$;
                        case "BZB": return MLMK^$;
                        case "BZZ": return MLMK^$;
                        case "BZS": return MLMK^$;
                        case "BZD": return MLMK^$;
                        case "BZP": return MLMK^$;
                        case "BSF": return MLMK^$;
                        case "BSM": return MLMK^$;
                        case "BSB": return MLMK^$;
                        case "BSZ": return MLMK^$;
                        case "BSS": return MLMK^$;
                        case "BSD": return MLMK^$;
                        case "BSP": return MLMK^$;
                        case "BDF": return MLMK^$;
                        case "BDM": return MLMK^$;
                        case "BDB": return MLMK^$;
                        case "BDZ": return MLMK^$;
                        case "BDS": return MLMK^$;
                        case "BDD": return MLMK^$;
                        case "BDP": return MLMK^$;
                        case "BPF": return MLMK^$;
                        case "BPM": return MLMK^$;
                        case "BPB": return MLMK^$;
                        case "BPZ": return MLMK^$;
                        case "BPS": return MLMK^$;
                        case "BPD": return MLMK^$;
                        case "BPP": return MLMK^$;
                        case "ZFF": return MLMK^$;
                        case "ZFM": return MLMK^$;
                        case "ZFB": return MLMK^$;
                        case "ZFZ": return MLMK^$;
                        case "ZFS": return MLMK^$;
                        case "ZFD": return MLMK^$;
                        case "ZFP": return MLMK^$;
                        case "ZMF": return MLMK^$;
                        case "ZMM": return MLMK^$;
                        case "ZMB": return MLMK^$;
                        case "ZMZ": return MLMK^$;
                        case "ZMS": return MLMK^$;
                        case "ZMD": return MLMK^$;
                        case "ZMP": return MLMK^$;
                        case "ZBF": return MLMK^$;
                        case "ZBM": return MLMK^$;
                        case "ZBB": return MLMK^$;
                        case "ZBZ": return MLMK^$;
                        case "ZBS": return MLMK^$;
                        case "ZBD": return MLMK^$;
                        case "ZBP": return MLMK^$;
                        case "ZZF": return MLMK^$;
                        case "ZZM": return MLMK^$;
                        case "ZZB": return MLMK^$;
                        case "ZZZ": return MLMK^$;
                        case "ZZS": return MLMK^$;
                        case "ZZD": return MLMK^$;
                        case "ZZP": return MLMK^$;
                        case "ZSF": return MLMK^$;
                        case "ZSM": return MLMK^$;
                        case "ZSB": return MLMK^$;
                        case "ZSZ": return MLMK^$;
                        case "ZSS": return MLMK^$;
                        case "ZSD": return MLMK^$;
                        case "ZSP": return MLMK^$;
                        case "ZDF": return MLMK^$;
                        case "ZDM": return MLMK^$;
                        case "ZDB": return MLMK^$;
                        case "ZDZ": return MLMK^$;
                        case "ZDS": return MLMK^$;
                        case "ZDD": return MLMK^$;
                        case "ZDP": return MLMK^$;
                        case "ZPF": return MLMK^$;
                        case "ZPM": return MLMK^$;
                        case "ZPB": return MLMK^$;
                        case "ZPZ": return MLMK^$;
                        case "ZPS": return MLMK^$;
                        case "ZPD": return MLMK^$;
                        case "ZPP": return MLMK^$;
                        case "SFF": return MLMK^$;
                        case "SFM": return MLMK^$;
                        case "SFB": return MLMK^$;
                        case "SFZ": return MLMK^$;
                        case "SFS": return MLMK^$;
                        case "SFD": return MLMK^$;
                        case "SFP": return MLMK^$;
                        case "SMF": return MLMK^$;
                        case "SMM": return MLMK^$;
                        case "SMB": return MLMK^$;
                        case "SMZ": return MLMK^$;
                        case "SMS": return MLMK^$;
                        case "SMD": return MLMK^$;
                        case "SMP": return MLMK^$;
                        case "SBF": return MLMK^$;
                        case "SBM": return MLMK^$;
                        case "SBB": return MLMK^$;
                        case "SBZ": return MLMK^$;
                        case "SBS": return MLMK^$;
                        case "SBD": return MLMK^$;
                        case "SBP": return MLMK^$;
                        case "SZF": return MLMK^$;
                        case "SZM": return MLMK^$;
                        case "SZB": return MLMK^$;
                        case "SZZ": return MLMK^$;
                        case "SZS": return MLMK^$;
                        case "SZD": return MLMK^$;
                        case "SZP": return MLMK^$;
                        case "SSF": return MLMK^$;
                        case "SSM": return MLMK^$;
                        case "SSB": return MLMK^$;
                        case "SSZ": return MLMK^$;
                        case "SSS": return MLMK^$;
                        case "SSD": return MLMK^$;
                        case "SSP": return MLMK^$;
                        case "SDF": return MLMK^$;
                        case "SDM": return MLMK^$;
                        case "SDB": return MLMK^$;
                        case "SDZ": return MLMK^$;
                        case "SDS": return MLMK^$;
                        case "SDD": return MLMK^$;
                        case "SDP": return MLMK^$;
                        case "SPF": return MLMK^$;
                        case "SPM": return MLMK^$;
                        case "SPB": return MLMK^$;
                        case "SPZ": return MLMK^$;
                        case "SPS": return MLMK^$;
                        case "SPD": return MLMK^$;
                        case "SPP": return MLMK^$;
                        case "DFF": return MLMK^$;
                        case "DFM": return MLMK^$;
                        case "DFB": return MLMK^$;
                        case "DFZ": return MLMK^$;
                        case "DFS": return MLMK^$;
                        case "DFD": return MLMK^$;
                        case "DFP": return MLMK^$;
                        case "DMF": return MLMK^$;
                        case "DMM": return MLMK^$;
                        case "DMB": return MLMK^$;
                        case "DMZ": return MLMK^$;
                        case "DMS": return MLMK^$;
                        case "DMD": return MLMK^$;
                        case "DMP": return MLMK^$;
                        case "DBF": return MLMK^$;
                        case "DBM": return MLMK^$;
                        case "DBB": return MLMK^$;
                        case "DBZ": return MLMK^$;
                        case "DBS": return MLMK^$;
                        case "DBD": return MLMK^$;
                        case "DBP": return MLMK^$;
                        case "DZF": return MLMK^$;
                        case "DZM": return MLMK^$;
                        case "DZB": return MLMK^$;
                        case "DZZ": return MLMK^$;
                        case "DZS": return MLMK^$;
                        case "DZD": return MLMK^$;
                        case "DZP": return MLMK^$;
                        case "DSF": return MLMK^$;
                        case "DSM": return MLMK^$;
                        case "DSB": return MLMK^$;
                        case "DSZ": return MLMK^$;
                        case "DSS": return MLMK^$;
                        case "DSD": return MLMK^$;
                        case "DSP": return MLMK^$;
                        case "DDF": return MLMK^$;
                        case "DDM": return MLMK^$;
                        case "DDB": return MLMK^$;
                        case "DDZ": return MLMK^$;
                        case "DDS": return MLMK^$;
                        case "DDD": return MLMK^$;
                        case "DDP": return MLMK^$;
                        case "DPF": return MLMK^$;
                        case "DPM": return MLMK^$;
                        case "DPB": return MLMK^$;
                        case "DPZ": return MLMK^$;
                        case "DPS": return MLMK^$;
                        case "DPD": return MLMK^$;
                        case "DPP": return MLMK^$;
                        case "PFF": return MLMK^$;
                        case "PFM": return MLMK^$;
                        case "PFB": return MLMK^$;
                        case "PFZ": return MLMK^$;
                        case "PFS": return MLMK^$;
                        case "PFD": return MLMK^$;
                        case "PFP": return MLMK^$;
                        case "PMF": return MLMK^$;
                        case "PMM": return MLMK^$;
                        case "PMB": return MLMK^$;
                        case "PMZ": return MLMK^$;
                        case "PMS": return MLMK^$;
                        case "PMD": return MLMK^$;
                        case "PMP": return MLMK^$;
                        case "PBF": return MLMK^$;
                        case "PBM": return MLMK^$;
                        case "PBB": return MLMK^$;
                        case "PBZ": return MLMK^$;
                        case "PBS": return MLMK^$;
                        case "PBD": return MLMK^$;
                        case "PBP": return MLMK^$;
                        case "PZF": return MLMK^$;
                        case "PZM": return MLMK^$;
                        case "PZB": return MLMK^$;
                        case "PZZ": return MLMK^$;
                        case "PZS": return MLMK^$;
                        case "PZD": return MLMK^$;
                        case "PZP": return MLMK^$;
                        case "PSF": return MLMK^$;
                        case "PSM": return MLMK^$;
                        case "PSB": return MLMK^$;
                        case "PSZ": return MLMK^$;
                        case "PSS": return MLMK^$;
                        case "PSD": return MLMK^$;
                        case "PSP": return MLMK^$;
                        case "PDF": return MLMK^$;
                        case "PDM": return MLMK^$;
                        case "PDB": return MLMK^$;
                        case "PDZ": return MLMK^$;
                        case "PDS": return MLMK^$;
                        case "PDD": return MLMK^$;
                        case "PDP": return MLMK^$;
                        case "PPF": return MLMK^$;
                        case "PPM": return MLMK^$;
                        case "PPB": return MLMK^$;
                        case "PPZ": return MLMK^$;
                        case "PPS": return MLMK^$;
                        case "PPD": return MLMK^$;
                        case "PPP": return MLMK^$;
                        default: return Error;
                    }
                default:
                    throw new NotImplementedException();
            }
        }
    }
}
